# Servidor
server.port=8080

# MongoDB — reemplazar con tu URL de Atlas o local
spring.data.mongodb.uri=PONER_URL_AQUI

# JWT — reemplazar con tu secret
jwt.secret=PONER_SECRET_AQUI
jwt.expiration=86400000